### ISSUE TITLE
Installation not working - WIndows 11/Python3.10

### ISSUE THREAD

**Issue by IneffableBunch** [yobix-ai/extractous#31] opened 2024-11-19 11:41 UTC
`pip install extractous 
`

returns:
 
`Collecting extractous
  Using cached extractous-0.2.0-cp38-abi3-win_amd64.whl.metadata (2.4 kB)
Using cached extractous-0.2.0-cp38-abi3-win_amd64.whl (40.0 MB)
Installing collected packages: extractous
Successfully installed extractous-0.2.0`

But 

`from extractous import Extractor`

Is not working? 

Windows 11, Python 3.10.15

**Comment by nmammeri** [comment] 2024-11-25 18:56
Thanks for reporting this. I'm surprised that you got this, this basically means extractous was not installed properly. It passed our ci tests. can you please try `pip install --verbose extractous` and report
thanks

**Comment by nmammeri** [comment] 2024-12-21 10:24
could not reproduce this issue. closing it

**Comment by nmammeri** [comment] 2024-12-21 10:25
could not reproduce this issue. closing it

**Closed by nmammeri** 2024-12-21 10:25 UTC
Labels: bug
